import mongoose from 'mongoose';

const FormDataSchema = new mongoose.Schema({
  photos: String,
  fullName: String,
  email: String,
  phoneNo: String,
  age: Number,
  sex: String,
  DOB: Date,
  Addhar_Voter: String,
  houseNo: String,
  landmark: String,
  village: String,
  state: String,
  nation: String,
  pincode: Number,
  purpose: String,
  patiantName: String,
  hospitalName: String,
  trakingDr: String,
  reason: String,
  studentName: String,
  studentDOB: Date,
  studentGender: String,
  studentCategary: String,
  studentPhoto: String,
  jobFullName: String,
  jobPosssition: String,
  jobDepartment: String,
  jobLocation: String,
  jobSalary: Number,
  employeeName: String,
  employeeId: String,
  employeeDepartment: String,
  employeeCDesignation: String,
  employeeRDepartment: String,
  employeeRTransfer: String,
  schemeName: String,
  schemePApplication: String,
  schemeApplyDate: Date,
  schemeMaritalStatus: String,
  schemeCategary: String,
  schemeAddhar: String,
  businessName: String,
  businessType: String,
  businessSector: String,
  businessRNo: String,
  businessDOE: Date,
  businessGST: String,
  businessAddress: String,
  utilityServiceInstallation: String,
  utilityProblem: String,
  policeApplicationNo: String,
  policeApplicationDate: Date,
  policeApplicationPlace: String,
  policeDetailInsidance: String,
  policeInvolveName: String,
  policeDeclaration: String,
  policephoto: String,
  nameProject: String,
  projectLocation: String,
  projectProblem: String,
  massage: String,
}, { timestamps: true });

export default mongoose.models.FormData || mongoose.model('FormData', FormDataSchema);
